### PR TITLE
Adds scripts for usual steps

### PR DESCRIPTION
**Pull request by DougReeder**
This makes it easy to perform steps from an IDE.

### CODE REVIEW

**Comment by DougReeder** [comment]
The `apply` script applies `hcce.yaml` and monitors until all deployments are ready.

**Review by Exairnous — CHANGES_REQUESTED** [review]
I agree that these seem to be nice convenience commands, but I'm not sure why this should affect IDEs at all.  Can you expand on that?

As to the scripts themselves.
We have had issues in the past with running terminal commands via the asynchronous Node functions and they are harder to read, so the synchronous versions should be used instead.

The new commands also need documentation in the readme.

**Comment by DougReeder** [comment]
Without these scripts, one needs a terminal window open to enter the kubectl commands. With the new scripts, in an IDE, one can click on the scripts to run them, and not keep a terminal window open.

The scripts work equally well when run from the command line.

**Review by Exairnous — APPROVED** [review]
Thanks for the updates.  This looks good now.  Merging.

**Pull request merged**
